# Generated by Django 5.2.16 on 2026-07-30 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdChainLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('TRANSIT', 'Transit'), ('DELIVERY', 'Delivery')], max_length=15)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('temperature_c', models.FloatField()),
                ('humidity_pct', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('is_within_threshold', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coldchain_logs', to='suppliers.batch')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coldchain_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_slug', models.SlugField(max_length=40, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='trust_badges/')),
                ('is_active', models.BooleanField(default=True)),
                ('regenerated_at', models.DateTimeField(blank=True, null=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_badge', to='accounts.hotelprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
