# Generated by Django 5.2.16 on 2026-07-30 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notif_type', models.CharField(choices=[('ORDER_UPDATE', 'Order Update'), ('LAB_RESULT_READY', 'Lab Result Ready'), ('COMPLIANCE_EXPIRY', 'Compliance Expiry'), ('VERIFICATION_STATUS', 'Verification Status'), ('ACCOUNT_APPROVAL', 'Account Approval'), ('GENERIC', 'Generic')], default='GENERIC', max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.CharField(blank=True, max_length=64)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
