# Generated by Django 5.2.16 on 2026-07-30 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text="icon key, e.g. 'leaf', 'flask', 'truck'", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('unit_default', models.CharField(default='kg', max_length=20)),
                ('expected_min_harvest_days', models.PositiveIntegerField(blank=True, help_text='Minimum biologically plausible days from sowing to harvest', null=True)),
                ('expected_max_harvest_days', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingredients/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='catalog.category')),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
    ]
