# Generated by Django 5.2.16 on 2026-07-30 09:53

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=apps.core.models.generate_public_id, editable=False, max_length=16, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('sowing_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField()),
                ('actual_harvest_days', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('is_growth_anomaly', models.BooleanField(default=False, editable=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('LISTED', 'Listed'), ('SOLD_OUT', 'Sold Out'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=25)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='batch_qr/')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.ingredient')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='accounts.supplierprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeoTaggedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='batch_photos/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('exif_locked', models.BooleanField(default=False, editable=False, help_text='True if lat/lng/timestamp were read from image EXIF data')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='suppliers.batch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.orderitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounts.supplierprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
