# Generated by Django 5.2.16 on 2026-07-30 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('labs', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='suppliers.batch'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.labprofile'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.labprofile'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_invoices', to='accounts.supplierprofile'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='suppliers.batch'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='accounts.labprofile'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='requested_tests',
            field=models.ManyToManyField(blank=True, to='labs.testtype'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='verification_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='labs.verificationrequest'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verification_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='labs.verificationrequest'),
        ),
    ]
